### Constants in Tensorflow:

In [1]:
import tensorflow as tf
sess=tf.Session()

In [12]:
c=tf.zeros([2,2],dtype=tf.int32)
print(sess.run(c))

[[0 0]
 [0 0]]


In [13]:
one_mat = tf.ones([3,4],dtype=tf.int32)
print(sess.run(one_mat))

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [15]:
const = tf.constant([1.0,2.5,3.5], shape=[2,3], dtype=tf.float32)
print(sess.run(const))

[[ 1.   2.5  3.5]
 [ 3.5  3.5  3.5]]


In [16]:
const2 = tf.ones_like(const)
print(sess.run(const2))

[[ 1.  1.  1.]
 [ 1.  1.  1.]]


In [17]:
const3 = tf.fill([3,4],10)
print(sess.run(const3))

[[10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]]


### Variables in Tensorflow

In [34]:
with tf.variable_scope("test",reuse=True):
    other_variable = tf.get_variable("other_variable", dtype=tf.int32,initializer=tf.constant([23, 45]))

In [40]:
sess.run(tf.global_variables_initializer())
print(sess.run(other_variable))

[23 42]


In [42]:
weights = tf.Variable(tf.random_normal([784, 200], stddev=0.35),
                      name="weights")
biases = tf.Variable(tf.zeros([200]), name="biases")

init=tf.global_variables_initializer()

sess.run(init)
print(sess.run([weights,biases]))

[array([[-0.21939828, -0.07273556,  0.34171635, ..., -0.46222925,
         0.2807669 ,  0.06331789],
       [ 0.35142779, -0.02968885, -0.44313264, ..., -0.10665154,
         0.17959514, -0.34015921],
       [ 0.01502059, -0.51342309, -0.27541849, ..., -0.12512161,
        -0.33644173, -0.43615729],
       ..., 
       [-0.49738923,  0.36618361,  0.4394407 , ...,  0.12127254,
         0.3148298 , -0.63946837],
       [ 0.4118261 , -0.09032049, -0.2591511 , ..., -0.30101448,
        -0.08249962, -0.26846528],
       [ 0.02382242, -0.07167004,  0.26801056, ...,  0.17659606,
        -0.16900332,  0.15986127]], dtype=float32), array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0

In [43]:
other_variable2 = tf.get_variable("other_variable2", dtype=tf.int32, initializer=tf.fill([3,4,5],5))
sess.run(tf.global_variables_initializer())
print(sess.run(other_variable2))

[[[5 5 5 5 5]
  [5 5 5 5 5]
  [5 5 5 5 5]
  [5 5 5 5 5]]

 [[5 5 5 5 5]
  [5 5 5 5 5]
  [5 5 5 5 5]
  [5 5 5 5 5]]

 [[5 5 5 5 5]
  [5 5 5 5 5]
  [5 5 5 5 5]
  [5 5 5 5 5]]]


### PlaceHolders

In [45]:
import numpy as np 
holder = tf.placeholder(tf.float32,shape=[20,20])
X = np.random.rand(20,20)
print(sess.run(holder,feed_dict={holder:X}))

[[ 0.17209724  0.80461723  0.1350431   0.59401518  0.94726288  0.19649386
   0.73657179  0.43380305  0.64248997  0.58813447  0.79103696  0.89464962
   0.75720483  0.23500204  0.25033751  0.90556383  0.07048714  0.42698976
   0.78791887  0.07309224]
 [ 0.25525904  0.1125716   0.59960401  0.3629868   0.80798477  0.14707009
   0.00992409  0.33116248  0.98595089  0.41656241  0.15885733  0.44693676
   0.13340008  0.92486185  0.94295466  0.74098384  0.46737272  0.03008246
   0.66500574  0.22218408]
 [ 0.53733331  0.25851971  0.55409515  0.25064048  0.90098566  0.39860296
   0.57015979  0.57244098  0.10964328  0.65435416  0.05936564  0.95691174
   0.35083926  0.96816969  0.59229875  0.97558224  0.20701441  0.48617047
   0.97650725  0.41741976]
 [ 0.66404897  0.68813789  0.56527638  0.97458833  0.76518196  0.29096124
   0.6191743   0.30624872  0.58835846  0.92121929  0.21874914  0.9350996
   0.6225397   0.85318941  0.6559549   0.89186245  0.3925679   0.04562543
   0.47244141  0.83585894]
 [ 0.

In [46]:
holder = tf.placeholder(tf.float32,shape=[None,2])
X = np.random.rand(20,2)
print(sess.run(holder,feed_dict={holder:X}))

[[ 0.16155344  0.27607998]
 [ 0.80375421  0.52414203]
 [ 0.3661415   0.87817276]
 [ 0.02638516  0.31826466]
 [ 0.71680403  0.27808437]
 [ 0.54245842  0.9762184 ]
 [ 0.23188633  0.94738179]
 [ 0.11651754  0.3576656 ]
 [ 0.33420601  0.79792577]
 [ 0.17158736  0.54167354]
 [ 0.78969353  0.79031599]
 [ 0.83909333  0.62792981]
 [ 0.81394893  0.16873442]
 [ 0.96459383  0.08731557]
 [ 0.25270748  0.85793334]
 [ 0.85823476  0.63202935]
 [ 0.50761092  0.70730871]
 [ 0.17660204  0.25007874]
 [ 0.56523222  0.05199148]
 [ 0.4836756   0.47687289]]


In [49]:
holder = tf.placeholder(tf.float32,shape=[None,1])
X = [[1],[2]]
print(sess.run(holder,feed_dict={holder:X}))

[[ 1.]
 [ 2.]]


In [50]:
holder = tf.placeholder(tf.float32,shape=[None,5])
X = [[1,2,3,4,5],[34,56,67,78,89]]
print(sess.run(holder,feed_dict={holder:X}))

[[  1.   2.   3.   4.   5.]
 [ 34.  56.  67.  78.  89.]]


### Matrix Multiplication

In [51]:
holder = tf.placeholder(tf.float32,shape=[None,2])
holder2 = tf.placeholder(tf.float32,shape=[2,None])
X = np.random.rand(10,2)
Y = np.random.rand(2,10)
mul=tf.matmul(holder,holder2)
print(sess.run(mul,feed_dict={holder:X,holder2:Y}))

[[ 0.6933502   0.54279339  0.82796746  0.12665495  0.6793313   0.1519531
   0.04021674  0.20852861  0.68707591  0.56194568]
 [ 0.22003463  0.25686184  0.29223737  0.12319821  0.17348504  0.12469931
   0.04011775  0.13507199  0.2482781   0.15903986]
 [ 0.09533933  0.21225378  0.1618039   0.1524266   0.02493262  0.14528829
   0.05002433  0.14073591  0.14365476  0.04588847]
 [ 0.37679589  0.88025081  0.65389729  0.64302069  0.07794126  0.61161572
   0.21108642  0.58991504  0.58253729  0.17191964]
 [ 0.78597981  1.11691844  1.11337245  0.63568652  0.52048391  0.62566596
   0.20777008  0.64485067  0.95812035  0.52263343]
 [ 0.7969259   0.97169399  1.07285285  0.48680469  0.60773736  0.48904848
   0.15868039  0.52290779  0.91400838  0.566576  ]
 [ 0.79438096  0.982162    1.07415569  0.49856409  0.59904361  0.49975374
   0.16256143  0.53228885  0.91593921  0.56167191]
 [ 0.46134901  0.95776099  0.75881034  0.66956908  0.15515324  0.64037603
   0.2196499   0.62456048  0.67036951  0.23786739]
 